# Generated by Django 5.1.2 on 2024-11-09 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, upload_to='planos')),
            ],
        ),
        migrations.CreateModel(
            name='clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=10, unique=True)),
                ('foto', models.ImageField(blank=True, upload_to='imagens_clin/')),
                ('desc', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nc.endereco')),
                ('especialidades', models.ManyToManyField(blank=True, to='nc.especialidades')),
                ('plano', models.ManyToManyField(blank=True, to='nc.plano')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=10, unique=True)),
                ('telefone', models.CharField(max_length=11)),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nc.endereco')),
                ('fav_clin', models.ManyToManyField(blank=True, related_name='clin_fav', to='nc.clinica')),
                ('hist_clin', models.ManyToManyField(blank=True, related_name='clin_hist', to='nc.clinica')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nc.clinica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nc.usuario')),
            ],
        ),
    ]
