# Generated by Django 5.1.2 on 2024-11-10 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='hist_clin',
        ),
        migrations.AddField(
            model_name='comentario',
            name='avaliacao',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nc.clinica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nc.usuario')),
            ],
        ),
    ]
