# Generated by Django 5.1.2 on 2024-11-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0002_remove_usuario_hist_clin_comentario_avaliacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historico',
            options={'ordering': ['data']},
        ),
        migrations.AlterUniqueTogether(
            name='historico',
            unique_together={('usuario', 'clinica')},
        ),
    ]
