# Generated by Django 5.1.2 on 2024-11-17 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0008_alter_clinica_foto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comentario',
            new_name='comentarios',
        ),
    ]
