# Generated by Django 5.1.2 on 2024-11-18 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0009_rename_comentario_comentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fav_clin',
        ),
        migrations.AlterField(
            model_name='clinica',
            name='foto',
            field=models.ImageField(blank=True, default='/batman-resolve-in-the-rain.jpg', null=True, upload_to='media'),
        ),
        migrations.CreateModel(
            name='favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nc.clinica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nc.usuario')),
            ],
            options={
                'ordering': ['data'],
                'unique_together': {('usuario', 'clinica')},
            },
        ),
    ]
