# Generated by Django 5.1.2 on 2024-11-18 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0010_remove_usuario_fav_clin_alter_clinica_foto_favorito'),
    ]

    operations = [
        migrations.CreateModel(
            name='mensagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nc.clinica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nc.usuario')),
            ],
        ),
    ]
