# Generated by Django 5.1.2 on 2024-11-18 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0011_mensagens'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagens',
            options={'ordering': ['data']},
        ),
    ]
