# Generated by Django 5.1.2 on 2024-11-19 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0013_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagens',
            name='clinica',
        ),
        migrations.RemoveField(
            model_name='mensagens',
            name='usuario',
        ),
        migrations.AddField(
            model_name='mensagens',
            name='chat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='nc.chat'),
            preserve_default=False,
        ),
    ]
